apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.web.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.web.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.web.name }}
    spec:
      containers:
        - name: {{ .Values.web.name }}
          image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
          ports:
            - name: http
              containerPort: 3000
